version: "3.9"
services:
  sdr:
    image: sdr
    build: ./images/sdr
    networks:
      - internal
    restart: always
    devices:
      - "/dev/bus/usb"
  mq:
    image: eclipse-mosquitto
    networks:
      - internal
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - "./images/mq/mosquitto.conf:/mosquitto/config/mosquitto.conf"
  app:
    image: nodered/node-red:latest-minimal
    networks:
      - internal
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - "./src/nodered:/data"
    depends_on:
      - sdr
      - mq
networks:
  internal:
