version: "3.8"
services:
  ui:
    image: nodered/node-red:latest-minimal
    restart: always
    ports: 
      - "1880:1880"
    depends_on:
      - mqtt
    volumes: 
      - "./data/ui:/data"
  sdr:
    image: sdr
    restart: always
    build:
      context: ./build/sdr
    depends_on:
      - mqtt
    devices:
      - "/dev/bus/usb/001"
  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./conf/mosquitto.conf:/mosquitto/config/mosquitto.conf"
