version: "3.8"
services:
  ui:
    image: nodered/node-red:latest-minimal
    restart: always
    ports: 
      - "1880:1880"
    depends_on:
      - sdr
    volumes: 
      - "./data/ui:/data"
      - "run:/run/dump1090"
  sdr:
    image: dump1090-fa
    restart: always
    env_file: default.env
    build:
      context: ./build/dump1090
    devices:
      - "/dev/bus/usb/001/008"
    volumes:
      - "run:/run/dump1090"
volumes:
  run:

