version: "3.8"
services:
  ui:
    image: adsb
    build:
      context: ./build 
    restart: always
    ports: 
      - "1880:1880"
    volumes: 
      - "./data/ui:/data"
    devices:
      - "/dev/bus/usb/001:/dev/bus/usb/001"

