version: "3.3"
services:
  recv:
    image: sdr-adsb
    build: .
    restart: unless-stopped
    ports:
      - "30001:30001"
      - "30002:30002"
      - "30003:30003"
      - "8080:8080"
    devices:
      - "/dev/bus/usb/001/005:/dev/bus/usb/001/005"
  ui:
    image: nodered/node-red
    restart: unless-stopped
    volumes:
      - "./data:/data"
    ports:
      - "1880:1880"
    depends_on: 
      - recv
