version: "3.8"
services:
  ui:
    image: nodered/node-red:latest-minimal
    restart: always
    ports: 
      - "1880:1880"
    depends_on:
      - sdr
    volumes: 
      - "./data/ui:/data"
      - "tmp:/data/tmp"
  sdr:
    image: dump1090-fa
    restart: always
    environment:
      STA_LAT: "39.9612"
      STA_LON: "-82.9988"    
    build:
      context: ./build/dump1090
    devices:
      - "/dev/bus/usb/001"
    volumes:
      - "tmp:/data"
volumes:
  tmp:
