version: "3.8"
services:
  ui:
    image: nodered/node-red
    restart: unless-stopped
    ports: 
      - "1880:1880"
    volumes: 
      - "./data/ui:/data"
    networks:
      - default
  sdr:
    image: sdr
    restart: unless-stopped
    build:
      context: ./build
    depends_on:
      - mqtt
    devices:
      - "/dev/bus/usb/001"
    networks:
      - default
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./conf/mosquitto.conf:/mosquitto/conf/mostquitto.conf"
