version: "3.7"
services:
    dump1090:
        build: ./dump1090
        image: flightmon/dump9010
        expose:
            - 30001
        ports: 
            - "8080:8080"
            - "30002:30002"
            - "30003:30003"
        networks:
            - default
        logging: 
            driver: none
    data:
        build: ./data
        image: flightmon/data
        networks:
            - default
    app:
        build: ./app
        image: flightmon/app
        ports: 
            - "80:80"
        networks:
            - default
